# Try catch

- Inside the `try` block, We write the code that can potentialy cause an error.
- Inside the `try` block, if we encounter any error, the further code stops executing and control shifts to the `catch` block.
- `catch` block takes an argument which is an `Error` instance.
