# Error handling with Promises

- When a promise is rejected, it `throws` an exception (Error instance).
- Or within the then block, if an error is encountered, execution will stop and program terminates.
- We can use the `catch` block to handle this error.
- In a promise chain, `catch` block handles errors for all the promises written above it.
- `catch` block does not stop the promise chain. It returns a new promise with value `undefined` by default which will be caught by the next then block.
- To really stop the chain, we have to rethrow the error, which return a rejected promise which will be caught by next catch block.
