# Promises

- The Promise object represents the eventual completion (or failure) of an asynchronous operation and its resulting value.
- It always produces a single value only.
- A Promise is in one of these states.
- `pending`: initial state, neither fulfilled nor rejected. Async operation has just started.
- `fulfilled`: meaning that the operation was completed successfully.
- `rejected`: meaning that the operation failed.


## How to create a Promise

- We pass a function that runs an async task and after it completes, we can change the state of our promise object.
- If it complets successfully, we can get the resultant value in the `then` block.
- If the task fails, value can be retrieved in the `catch` block.

``` javascript

const promise = new Promise((resolve, reject) => {
  // async operation
  setTimeout(() => {
    resolve("I have completed");
  }, 2000);
});

promise.then((data) => {
  console.log(data);
});

```


``` javascript

const promise = new Promise((resolve, reject) => {
  // async operation
  setTimeout(() => {
    reject("Something went wrong");
  }, 2000);
});

promise.catch((data) => {
  console.log(data);
});

```

## Chaining promises

- Whenever we return something from within a `then` block, a new promise is returned with that value.

``` javascript

const promise = new Promise((resolve, reject) => {
  resolve("Hey there");
});

const b = promise.then((data) => data); // returns a new promise with value "Hey there".

b.then((data) => console.log(data));

```

- So, we get a new promise and we know on every promise we can add `then` and `catch` blocks.

``` javascript

const promise = new Promise((resolve, reject) => {
  resolve("Hey there");
});

promise
  .then((data) => data)
  .then((data) => {
    console.log(data);
  });

```

``` javascript

function getPosts() {
  return fetch("https://jsonplaceholder.typicode.com/posts");
}

function getPostDetails(postId) {
  return fetch(`https://jsonplaceholder.typicode.com/posts/${postId}`);
}

function getUserDetails(userId) {
  return fetch(`https://jsonplaceholder.typicode.com/posts/${userId}`);
}

getPosts()
  .then((res) => res.json())
  .then((posts) => getPostDetails(posts[0].id))
  .then((res) => res.json())
  .then((postDetails) => {
    console.log(postDetails);
  });

```


## Error Handling

- `catch` blocks are used for error handling in promise chains.
- A `catch` block catches errors for all promises present above it.
- `catch` block does not stop the promise chain. If we have then callback written after a catch, it will still execute by default.

``` javascript

function asyncTask1() {
  return new Promise((resolve, reject) => {
    reject("Task 1 failed");
  });
}

function asyncTask2() {
  return new Promise((resolve, reject) => {
    reject("Task 2 completed");
  });
}

asyncTask1()
  .then((data) => {
    console.log("TASK 1::", data);
    return asyncTask2();
  })
  .catch((error) => {
    console.log(error); // Task 1 failed"
  })
  .then((data) => {
    console.log("TASK2::", data); // undefined
  })
  .catch((error) => {
    console.log(error);
  });

```

- Even though task1 has failed, then block of task2 will still execute.
- Eroor caught by the first catch by default does not propogate to the next catch.
